import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: {
    alphaTab: ["introduction", "contributing"],
    "Getting Started (Web)": [
      "getting-started/installation-web",
      "getting-started/configuration-web",
    ],
    "Getting Started (.net)": [
      "getting-started/installation-net",
      "getting-started/configuration-net",
    ],
    Guides: [
      "guides/lowlevel-apis",
      "guides/styling-player",
      "guides/multiple-soundfonts",
      "guides/song-details",
      "guides/exporter",
      "guides/handling-midi-events",
      "guides/nodejs",
      "guides/breaking-changes-095-096",
      "guides/breaking-changes-097-098",
    ],
    "API Reference": [
      {
        type: "category",
        label: "Settings",
        link: {
          type: "doc",
          id: "reference/settings",
        },
        className: "reference-item",
        collapsible: false,
        collapsed: true,
        items: [
          {
            type: "autogenerated",
            dirName: "reference/settings",
          },
        ],
      },
      {
        type: "category",
        label: "API",
        link: {
          type: "doc",
          id: "reference/api",
        },
        className: "reference-item",
        collapsible: false,
        collapsed: true,
        items: [
          {
            type: "autogenerated",
            dirName: "reference/api",
          },
        ],
      },
      {
        type: "doc",
        label: "Data Model",
        id: "reference/score",
      },
      {
        type: "category",
        label: "ScoreRenderer",
        link: {
          type: "doc",
          id: "reference/scorerenderer",
        },
        className: "reference-item",
        collapsible: false,
        collapsed: true,
        items: [
          {
            type: "autogenerated",
            dirName: "reference/scorerenderer",
          },
        ],
      },
      {
        type: "category",
        label: "AlphaSynth",
        link: {
          type: "doc",
          id: "reference/alphasynth",
        },
        className: "reference-item",
        collapsible: false,
        collapsed: true,
        items: [
          {
            type: "autogenerated",
            dirName: "reference/alphasynth",
          },
        ],
      },
    ],
  },
  tutorial: {
    Tutorials: ["tutorials"],
    "Tutorial (Web)": [
      "tutorial-web/introduction",
      "tutorial-web/setup",
      "tutorial-web/viewport",
      "tutorial-web/track-selector",
      "tutorial-web/controls",
      "tutorial-web/player",
      "tutorial-web/conclusion",
    ],
    "Tutorial (.net)": [
      "tutorial-net/introduction",
      "tutorial-net/setup",
      "tutorial-net/viewport",
      "tutorial-net/track-selector",
      "tutorial-net/controls",
      "tutorial-net/player",
      "tutorial-net/conclusion",
    ],
  },
  alphaTex: {
    alphaTex: [
      "alphatex/introduction",
      "alphatex/metadata",
      "alphatex/notes",
      "alphatex/bar-metadata",
      "alphatex/tracks-staves",
      "alphatex/beat-effects",
      "alphatex/note-effects",
    ],
  },
  showcase: {
    Showcase: [
      "showcase/introduction",
      "showcase/general",
      "showcase/layouts",
      "showcase/music-notation",
      "showcase/guitar-tabs",
      "showcase/special-tracks",
      "showcase/special-notes",
      "showcase/effects",
    ],
  },
};

module.exports = sidebars;
