name: Deploy
on: 
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
      with: 
        ref: 'main'
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install
    - run: npm install @coderline/alphatab@latest
    - run: npm run build
    - name: Package Zip
      run: zip -qq -r ../website.zip .
      working-directory: ./build
    - run: ls -l website.zip
    - uses: actions/upload-artifact@v4
      with: 
        name: website
        path: website.zip
    - name: Push Zip To Server
      run: |
        curl --request POST \
        --url https://docs-deploy.alphaTab.net/ \
        --header 'authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}' \
        --header 'branch: website' \
        -F 'website=@./website.zip' \
        --fail-with-body
